id: com.github.moussetc.mattermost.plugin.giphy
name: Giphy
description: Add Giphy features to Mattermost
version: '0.1.0'
backend:
    executable: plugin
settings_schema:
    settings:
        - key: APIKey
          type: text
          display_name: Giphy API Key
          help_text: Configure your Giphy API Key (the default key is the beta public key, which is subject to rate limit constraints).
          default: dc6zaTOxFJmzC
        - key: Rating
          type: text
          display_name: GIF Rating
          help_text: Choose the MPAA-style rating (y, g, pg, pg-13, r...) used to filter results or leave empty for no rating filtering.
        - key: Rendition
          type: dropdown
          display_name: Rendition style
          help_text: Select the rendition style used to display GIFs.
          default: fixed_height_small
          options:
            - display_name: Height set to 200px. Good for mobile use.
              value: fixed_height
            - display_name: Static preview image for fixed_height
              value: fixed_height_still
            - display_name: Height set to 100px. Good for mobile keyboards.
              value: fixed_height_small
            - display_name: Static preview image for fixed_height_small
              value: fixed_height_small_still
            - display_name: Width set to 200px. Good for mobile use.
              value: fixed_width
            - display_name: Static preview image for fixed_width
              value: fixed_width_still
            - display_name: Width set to 100px. Good for mobile keyboards
              value: fixed_width_small
            - display_name: Static preview image for fixed_width_small
              value: fixed_width_small_still
            - display_name: File size under 2mb.
              value: downsized
            - display_name: File size under 8mb.
              value: downsized_large
            - display_name: Static preview image for downsized
              value: downsized_still
            - display_name: Original file size and file dimensions. Good for desktop use.
              value: original
            - display_name: Preview image for original
              value: original_still
            - display_name: Duration set to loop for 15 seconds. Only recommended for this exact use case.
              value: looping
        - key: Language
          type: dropdown
          display_name: Language
          help_text: Select the language used to search GIFs.
          default: en
          options:
            - display_name: English
              value: en
            - display_name: Español
              value: es
            - display_name: Français
              value: fr
            - display_name: Português
              value: pt
            - display_name: Bahasa Indonesia
              value: id
            - display_name: العربية
              value: ar
            - display_name: Türkçe
              value: tr
            - display_name: ไทย
              value: th
            - display_name: Tiếng Việt
              value: vi
            - display_name: Deutsch
              value: de
            - display_name: Italiano
              value: it
            - display_name: 日本語 (にほんご)
              value: ja
            - display_name: Chinese Simplified
              value: zh-CN
            - display_name: Chinese Traditional
              value: zh-TW
            - display_name: русский
              value: ru
            - display_name: 한국어 
              value: ko
            - display_name: Polszczyzna
              value: pl
            - display_name: Nederlands 
              value: nl
            - display_name: Română
              value: ro
            - display_name: magyar
              value: hu
            - display_name: Svenska
              value: sv
            - display_name: čeština 
              value: cs
            - display_name: हिन्दी, हिंदी
              value: hi
            - display_name: বাংলা
              value: bn
            - display_name: dansk
              value: da
            - display_name: فارسی
              value: fa
            - display_name: Filipino
              value: tl
            - display_name: suomi
              value: fi
            - display_name: עברית
              value: he
            - display_name: بهاس ملايو
              value: ms
            - display_name: Norsk
              value: no
            - display_name: Українська
              value: uk
    footer: |
        Powered by Giphy.
        
        * To get your own Giphy API key, follow the instructions in the [developers documentation](https://developers.giphy.com/docs).

        * For more information on the rendering styles, see the [Giphy API guide](https://developers.giphy.com/docs/#rendition-guide).

        * To report an issue, make a suggestion or a contribution, or fork your own version of the plugin, [check the repository](https://github.com/moussetc/mattermost-plugin-giphy).
