name: Build CI

on: 
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

env:
  GO111MODULE: on

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go environment
      uses: actions/setup-go@v4
      with:
        go-version: '1.16.7'

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Build
      run: make

    - name: Publish
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*