name: Build CI

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

env:
  GO111MODULE: on

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go environment
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v7

    - name: Build
      run: make

    - name: Publish
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
