name: Build CI

on: 
  push:
    branches:
      - 'master'
      - 'release/**'
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

env:
  GO111MODULE: on

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go environment
      uses: actions/setup-go@v3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.16.7
        # Whether to download only stable versions
        stable: true

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v3

    - name: Build
      run: make

    - name: Publish
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*